//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THCNPM_Lab5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSINHVIEN
    {
        public string MaSv { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string MaLop { get; set; }
        public string MaTinh { get; set; }
        public double DTB { get; set; }
    }
}
